// <auto-generated />
namespace EF.DataAccess.MigrationsBaga
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ComplexComplexType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComplexComplexType));
        
        string IMigrationMetadata.Id
        {
            get { return "201607051813016_ComplexComplexType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
