// <auto-generated />
namespace EF.DataAccess.MigrationsBagaFluent
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrecisionAndScale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrecisionAndScale));
        
        string IMigrationMetadata.Id
        {
            get { return "201607051613078_PrecisionAndScale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
